### ISSUE TITLE
Got panic! The impossible happened 

### ISSUE THREAD

**Issue by ahdyt** [simmsb/calamity#46]
Hi there, I got ghc pnic the impossible happened while trying cabal run and build calamity.

OS : Nixos
ghc : 8.10.4

**Comment by simmsb** [comment]
Hi, can you send the exact error ghc emits, thanks.

**Comment by ahdyt** [comment]
Oh got it fixed by installing missing libraries in cabal. tho I just do copy-paste and run the I think "Hello, world" example in README.md, tho there's a lot libraries that I don't add yet.
