### ISSUE TITLE
No HasID instances for FullContext and LightContext?

### ISSUE THREAD

**Issue by MorrowM** [simmsb/calamity#50]
Is there a reason `FullContext` and `LightContext` don't have `HasID Channel`/`Message`/`User` instances? It'd be quite nice for e.g. `invoke $ CreateMessage ctx $ def ...` rather than having to use `ctx ^. #channel` all the time. 
If not I'd be glad to make a PR.

**Comment by simmsb** [comment]
I can't remember a reason for not having HasID on Context if there was a reason originally, so go ahead.
