### ISSUE TITLE
Not handling event: "GUILD_AUDIT_LOG_ENTRY_CREATE"

### ISSUE THREAD

**Issue by Miezhiko** [simmsb/calamity#57]
also Not handling event: "THREAD_MEMBERS_UPDATE"

https://github.com/simmsb/calamity/blob/master/calamity/Calamity/Client/Client.hs#L431

**Comment by simmsb** [comment]
Calamity currently doesn't have the code to handle these events, they're explicitly parsed and logged at the debug level as not handled instead of causing a parse error somewhere else
