### ISSUE TITLE
Question: how invole sendMssage on IO () scope

### ISSUE THREAD

**Issue by Miezhiko** [simmsb/calamity#58]
Trying to `reply @Text message myVal` inside just `IO ()` method

I'm starting some separated polling loop the same time with a bot and want to have ability to call bot functionality such sendMessage etc there too.

```haskell
    • Couldn't match expected type: IO a0
                  with actual type: Polysemy.Internal.Sem
                                      r0 (Either RestError Message)
```

as far a I understand I still can do it with polysemy eval?

please provide minimal example

**Comment by simmsb** [comment]
One way is to some some function like the following:

```hs
bindSemToIO :: forall r p a. P.Member (P.Final IO) r => (p -> P.Sem r a) -> P.Sem r (p -> IO (Maybe a))
bindSemToIO m = P.withStrategicToFinal $ do
  istate <- P.getInitialStateS
  m' <- P.bindS m
  ins <- P.getInspectorS
  P.liftS $ pure (\x -> P.inspect ins <$> m' (istate $> x))
```

This works by capturing the state of the `Sem` and packaging it into the final monad.
(The reason for the `Maybe` is that a `Sem a` doesn't always yield an `a` if an exception effect is in use)

Using this is most likely fine because you can't use plain `State` effects with calamity anyway, but be aware that if you use this anywhere else local state changes won't escape the `IO` packaged action and every time you execute the action any local state will be the same as it was when the state was initially captured.

**Comment by Miezhiko** [comment]
I am very sorry but this looks way too complicated for me to understand this code and usage. can't even find what is `$>`

that's how I was trying to use it :-/

```haskell
import           Control.Applicative
import           Control.Monad

import           Optics
import           Optics.TH

import           Calamity

import           Data.Text           (Text)
import qualified Data.Text           as T

import           Polysemy            (Member)
import qualified Polysemy            as P
import qualified Polysemy.Embed      as P
import qualified Polysemy.Final      as P
import qualified Polysemy.State      as P

bindSemToIO ∷ forall r p a. P.Member (P.Final IO) r
            => (p -> P.Sem r a)
            -> P.Sem r (p -> IO (Maybe a))
bindSemToIO m = P.withStrategicToFinal $ do
  istate  <- P.getInitialStateS
  m'      <- P.bindS m
  ins     <- P.getInspectorS
  P.liftS $ pure (\x -> P.inspect ins <$> m' (istate $> x))

replyBotEff ∷ Snowflake Channel
           -> Snowflake Message
           -> String
           -> IO ()
replyBotEff _chanId mesgId stxt =
  void $ bindSemToIO
       $ void $ reply @Text mesgId (T.pack stxt)
```

**Comment by simmsb** [comment]
Ah it's a bit weird to use but here's how it works:

The parameter to the function `(p -> P.Sem r a)` should be some function that takes a parameter and returns a polysemy action, so something like `\(id, text) -> void $ reply id text` (which will have the type `P.Member ... r  => (Snowflake Channel, Text) -> P.Sem r ...`

Using this `bindSemToIO (\(id, text) -> ...)` will get you something with the type `P.Member ... r => P.Sem r ((Snowflake Channel, Text) -> IO (Maybe ...))`

You can then use that action inside some `Sem` context to get your `(Channel, Text) -> IO (Maybe ...)` that you can then pass around wherever you want and use within an `IO` context.

```hs
foo :: P.Sem r ()
foo = do
    act <- bindSemToIO (\(id, text) -> void $ reply id text)
    P.embed . forkIO $ do
        act foo bar
```

The `Sem r (p -> IO (Maybe a))` action serves to collect the state of the `Sem` and package it up in an `IO`

**Comment by Miezhiko** [comment]
still wasn't able to do it, need to convert message from snowflake, many types errors

**Comment by Miezhiko** [comment]
now I understand better. but I don't have Message, only ID (Snowflake Message), is it possible to get Message by having only numbers of message channel user...?
